### ISSUE TITLE
3 monitors OK, but how can I get it to work with 4 ?

### ISSUE THREAD

**Issue by benintech** [liskin/hybrid-screenclone#11]
Hi,

I got it to work just fine with 3 monitors (laptop monitor + VGA + DisplayPort).

But not with 4 monitors (laptop monitor + VGA + DisplayPort + HDMI)

I modified screenclone.cc at line 90, and put "num_virtual=2"
Then I modified the "Device" section of xorg.conf.nvidia file and put : Option "Virtuals" "2"

After doing that:
xrandr recognizes all 4 monitors:
LVDS1...
VGA1...
VIRTUAL1...
VIRTUAL2...

Then I did 
screenclone -d :8 -x 2    WORKS FINE, I got my VIRTUAL1 monitor working
screenclone -d :8 -x 3     NOT WORKING, still blank screen (but nevertheless activated by optirun)

What am I missing ?

(Debian 7.6 / amd64 / xserver-xorg-video-intel 2.20.14)

**Comment by liskin** [comment]
Well, my version of screenclone never worked with more than one cloned output. See the other issues for attempts to fix this. I never got to merge any of them as I didn't have a setup to test it and was otherwise too lazy to do it anyway.

Also, hybrid-screenclone is obsolete and should not be used these days (I certainly do not intend to develop it any further). The upstream xf86-video-intel driver has supported virtual outputs and has had tools for cloning any number of them for more than a year now. See http://cgit.freedesktop.org/xorg/driver/xf86-video-intel/tree/tools/.

**Comment by benintech** [comment]
ok thanks
I finally just go it to work using puetzk's fork : https://github.com/puetzk/hybrid-screenclone
so now my 4 monitors are up and running and i'm a happy man !!

(could be usefull for people still using older intel video driver, given that latest stable debian 7.6 still uses version 2.19 of xserver-xorg-video-intel)

anyway, thanks for that great program and thanks for the intel pointer, I'll have a look into it

**Comment by liskin** [comment]
Well, I find it easier to apt-get source && dpkg-buildpackage a newer intel driver than do the same thing with the old one and on top of that git clone and build hybrid-screenclone, so using old debian doesn't seem like a good excuse. :-)

But yeah, the new one may not be stable with certain hardware, or there may be something else. I'm glad that you got it working.
