### ISSUE TITLE
screenclone-runx.sample

### ISSUE THREAD

**Issue by rickysarraf** [liskin/hybrid-screenclone#5]
What is https://github.com/liskin/hybrid-screenclone/blob/master/screenclone-runx.sample supposed to do?

It is heavily based on your setup.
What is sudoX in it?
What is tp420_nvidia.sh in it?

From the name, it looks like we can run apps under a different X server and draw the output on display :0.0
If so, this would be a perfect trick to get the Hi-Def video working. Can you please describe more of the scripts?

**Comment by liskin** [comment]
sudoX is just a wrapper around "sudo X", tp420_nvidia.sh uses bbswitch to turn on/off the nvidia card so that it doesn't consume power.

screenclone is primarily meant for running apps on :0 (integrated graphics card) and cloning an entire Xinerama output to a different X server, as a means to get triple head on a ThinkPad with Optimus. If you want to run apps on nvidia and display them on the integrated card, bumblebee is what you're looking for. Otherwise, google a bit, some good people have written howtos for screenclone.

**Comment by liskin** [comment]
Oh, and to answer your question, screenclone-runx.sample is a script I use to start an X server on nvidia cloning one of the screens on intel.

**Comment by rickysarraf** [comment]
Thanks. I have been able to have the dual setup done. Now the next task is to play videos with nvidia vdpau on Laptop's display.

**Comment by rickysarraf** [comment]
By the way, do you have a link of the howto? I haven't found a single link that make vdpau work on the single display (i.e. when not connected to external monitor)

**Comment by liskin** [comment]
Quick googling for "bumblebee vdpau" got me this: http://askubuntu.com/questions/102508/hybrid-dump-for-vdpau-accelerated-video-playing-on-ubuntu-11-10-with-bumblebee-3
Never tried anything like that, though.
